services:
  app:
    image: ${DOCKER_IMAGE}
    volumes:
      - ./logs:/logs
    dns:
      - 8.8.8.8 # dns resolution issue fix
    environment:
      SPRING_PROFILES_ACTIVE: $SPRING_PROFILES_ACTIVE
      DATABASE_URL: "jdbc:postgresql://${AWS_RDS_HOSTNAME}:${AWS_RDS_PORT}/${AWS_RDS_DB_NAME}"
      DATABASE_USERNAME: "$AWS_RDS_USERNAME"
      DATABASE_PASSWORD: "$AWS_RDS_PASSWORD"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    depends_on:
      - app
