spring.datasource.url=${DATABASE_URL}?ssl=true&sslmode=require
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable Liquibase for dev environment, disable JPA auto-DDL
spring.liquibase.enabled=true
spring.liquibase.analytics-enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
