name: Build and deploy api

on:
    pull_request: 
    # push:
      branches: [main]

jobs:
    build:
        name: Build docker image
        runs-on: ubuntu-latest

        env:
          TAG: johnakins/n7b3v9c1x5z8a2-analytics-repo:event-ingestion-service-${{ vars.GH_BRANCH }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java
              uses: actions/setup-java@v4
              with: 
                java-version: 21
                distribution: 'temurin'
                cache: maven

            - name: Build app
              run: |
                     mvn clean
                     mvn -B package

            - name: Build docker image
              uses: docker/build-push-action@v4
              with: 
                context: .
                dockerfile: Dockerfile
                push: false
                tags: ${{ env.TAG }}
                # Also tag with commit hash for traceability: myuser/myimage:${{ github.sha }}

            - name: Login to docker hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Push docker image to docker hub
              uses: docker/build-push-action@v4
              with: 
                context: .
                dockerfile: Dockerfile
                push: true
                tags: ${{ env.TAG }}
