name: Infra Provisioning

on:
    pull_request:
      branches: [main]

jobs:
    provision_infra:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: "infra"

        env:
          # Variables
          TF_VAR_region: ${{ vars.TF_VAR_REGION }}
          TF_VAR_default_vpc: ${{ vars.TF_VAR_DEFAULT_VPC }}
          TF_VAR_ec2_instance_type: ${{ vars.TF_VAR_EC2_INSTANCE_TYPE }}
          TF_VAR_ec2_ip_address: ${{ vars.TF_VAR_EC2_IP_ADDRESS }}
          TF_VAR_rdsconfig_allocated_storage: ${{ vars.TF_VAR_RDSCONFIG_ALLOCATED_STORAGE }}
          TF_VAR_rdsconfig_engine_version: ${{ vars.TF_VAR_RDSCONFIG_ENGINE_VERSION }}
          TF_VAR_rdsconfig_INSTANCE_CLASS: ${{ vars.TF_VAR_RDSCONFIG_INSTANCE_CLASS }}
          TF_VAR_rdsconfig_storage_type: ${{ vars.TF_VAR_RDSCONFIG_STORAGE_TYPE }}
          TF_VAR_rdsconfig_engine: ${{ vars.TF_VAR_RDSCONFIG_engine }}
          TF_VAR_SUBNET_A: ${{ vars.TF_VAR_SUBNET_A }}
          TF_VAR_SUBNET_B: ${{ vars.TF_VAR_SUBNET_B }}
          # Secrets
          TF_VAR_rdsconfig_identifier: ${{ secrets.TF_VAR_RDSCONFIG_IDENTIFIER }}
          TF_VAR_rdsconfig_db_name: ${{ secrets.TF_VAR_RDSCONFIG_DB_NAME }}
          TF_VAR_rdsconfig_username: ${{ secrets.TF_VAR_RDSCONFIG_USERNAME }}
          TF_VAR_rdsconfig_password: ${{ secrets.TF_VAR_RDSCONFIG_PASSWORD }} 
          TF_VAR_ssh_private_key: ${{ secrets.TF_VAR_SSH_PRIVATE_KEY }}
          TF_VAR_EC2_AMI: ${{ secrets.TF_VAR_ec2_ami }}

        steps:

          - name: checkout
            uses: actions/checkout@v4
            with:
              sparse-checkout: "infra"
              sparse-checkout-cone-mode: false

          - name: Configure AWS Credentials # not needed for tf, just passed those cred as env vars
            uses: aws-actions/configure-aws-credentials@v5.0.0
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: $TF_VAR_region

          - name: terraform setup
            uses: hashicorp/setup-terraform@v3

          - name: initial terraform
            run: terraform init

          - name: terraform plan
            run: terraform plan -no-color

          - name: terraform apply
            run: terraform apply -auto-approve

          # - name: terraform destroy
          #   run: terraform apply -destroy -auto-approve