name: dummy

on: 
    push:
      branches: [main]

jobs:
  dummy:
    name: dummy
    runs-on: ubuntu-latest

    steps:
        - name: dummy
          run: echo "dummy"
          
# name: Security Scan

# on:
#     pull_request:
#     # push:
#         branches: [main]
#     schedule:
#         # Run weekly on Mondays at 9 AM UTC
#         - cron: '0 9 * * 1'

# jobs:
#     security-scan:
#         name: Run security scans
#         runs-on: ubuntu-latest

#         steps:
#         - name: Checkout code
#           uses: actions/checkout@v4

#         - name: Set up Java
#           uses: actions/setup-java@v4
#           with:
#             distribution: 'temurin'
#             java-version: 21
#             cache: 'maven'

#         - name: Run OWASP Dependency Check
#           run: mvn org.owasp:dependency-check-maven:check

#         - name: Upload security scan results
#           uses: actions/upload-artifact@v4
#           with:
#             name: security-scan-results
#             path: target/dependency-check-report.html
